/**
 * Booking Status Constants
 */
const BOOKING_STATUS = Object.freeze({
  CONFIRMED: 'CONFIRMED',
  AGREEMENT_DONE: 'AGREEMENT_DONE',
  PENDING_DOCS: 'PENDING_DOCS',
  CANCELLED: 'CANCELLED',
});

const BOOKING_STATUS_VALUES = Object.values(BOOKING_STATUS);

const PAYMENT_STATUS = Object.freeze({
  TOKEN_RECEIVED: 'TOKEN_RECEIVED',
  AGREEMENT_PAID: 'AGREEMENT_PAID',
  PARTIAL_TOKEN: 'PARTIAL_TOKEN',
  PENDING: 'PENDING',
});

const PAYMENT_STATUS_VALUES = Object.values(PAYMENT_STATUS);

module.exports = {
  BOOKING_STATUS,
  BOOKING_STATUS_VALUES,
  PAYMENT_STATUS,
  PAYMENT_STATUS_VALUES,
};
